apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-deployment
  labels:
    app: client-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: client-service
          image: {{ .Values.clientService.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.clientService.port }}