apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client-service
spec:
  type: ClusterIP
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: {{ .Values.clientService.port }}