apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres1-deployment
  labels:
    app: postgres1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres1
  template:
    metadata:
      labels:
        app: postgres1
    spec:
      containers:
        - name: postgres1
          image: {{ .Values.postgres1.image }}
          ports:
            - containerPort: {{ .Values.postgres1.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres1.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres1.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres1.database }}