apiVersion: v1
kind: Service
metadata:
  name: postgres2
  labels:
    app: postgres2
spec:
  type: ClusterIP
  selector:
    app: postgres2
  ports:
    - protocol: TCP
      port: 5432
      targetPort: {{ .Values.postgres2.port }}