apiVersion: v1
kind: Service
metadata:
  name: postgres1
  labels:
    app: postgres1
spec:
  type: ClusterIP
  selector:
    app: postgres1
  ports:
    - protocol: TCP
      port: 5432
      targetPort: {{ .Values.postgres1.port }}