apiVersion: v1
kind: Service
metadata:
  name: schedule-service
  labels:
    app: schedule-service
spec:
  type: ClusterIP
  selector:
    app: schedule-service
  ports:
    - protocol: TCP
      port: {{ .Values.scheduleService.port }}
      targetPort: {{ .Values.scheduleService.port }}