apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-deployment
  labels:
    app: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
        - name: telegram-bot
          image: {{ .Values.telegramBot.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.telegramBot.port }}