apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-service
  labels:
    app: telegram-bot
spec:
  type: ClusterIP
  selector:
    app: telegram-bot
  ports:
    - protocol: TCP
      port: {{ .Values.telegramBot.port }}
      targetPort: {{ .Values.telegramBot.port }}