apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  type: NodePort  
  selector:
    app: zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: {{ .Values.zipkin.port }}
      nodePort: 30000