info:
  app:
    name: "Client Module"
    description: "Client Module for Fitness Application"
    version: "1.0.0"
  author: "Хазиев Егор Игоревич"
  contact:
    email: "egor5.87@mail.ru"

# Server Configuration
server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

management:
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: "ClientModule"

  #H2
#  datasource:
#    url: jdbc:h2:mem:testdb;
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  jpa:
##    hibernate:
##      ddl-auto: create
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#PostgreSQL
  datasource:
#    url: jdbc:postgresql://postgres1:5432/people
    url: jdbc:postgresql://localhost:5432/people
    driverClassName: org.postgresql.Driver
    username: su
    password: su
  jpa:
    # hibernate:
    #   ddl-auto: update, create, validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#liquibase
  liquibase:
#    clear-checksums: true
    enabled: true
    drop-first: false
    change-log: classpath:db.changelog-client-module.yml


