server:
  port: 8083

management:
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

spring:
  application:
    name: "ScheduleModule"
##H2
#  datasource:
#    url: jdbc:h2:mem:testdb;
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  jpa:
##    hibernate:
##      ddl-auto: create
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  #PostgreSQL
  datasource:
#    url: jdbc:postgresql://postgres2:5432/schedules
    url: jdbc:postgresql://localhost:5433/schedules
    driverClassName: org.postgresql.Driver
    username: su
    password: su
  jpa:
    # hibernate:
    #   ddl-auto: update  # или create, validate — в зависимости от задачи
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #liquibase
  liquibase:
    #    clear-checksums: true
    enabled: true
    drop-first: false
    change-log: classpath:db.changelog-schedule-module.yml