### GET request to retrieve a schedule by ID
GET http://localhost:8080/api/schedules/1

### GET request to retrieve all schedules
GET http://localhost:8080/api/schedules

### POST request to create a new schedule
POST http://localhost:8080/api/schedules?employeeId=123&clientIds=1,2,3
Content-Type: application/json

{
  "dateTimeStart": "2024-08-02T14:00:00",
  "dateTimeEnd": "2024-08-02T15:00:00",
  "roomId": 1,
  "trainingTypeId": 1,
  "comment": "Afternoon Yoga Session",
  "numberTr": 20
}

### PUT request to update a schedule
PUT http://localhost:8080/api/schedules/1?employeeId=456&clientIds=4,5,6
Content-Type: application/json

{
  "dateTimeStart": "2024-08-03T10:00:00",
  "dateTimeEnd": "2024-08-03T11:00:00",
  "roomId": 2,
  "trainingTypeId": 2,
  "comment": "Updated Morning Pilates",
  "numberTr": 25
}

### DELETE request to delete a schedule
DELETE http://localhost:8080/api/schedules/1