version: '3.8'

services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  postgres1:
    image: postgres:15
    container_name: postgres1
    environment:
      POSTGRES_USER: su
      POSTGRES_PASSWORD: su
      POSTGRES_DB: people
    ports:
      - "5432:5432"
  #    volumes:
  #      - pgdata1:/var/lib/postgresql/data

  postgres2:
    image: postgres:15
    container_name: postgres2
    environment:
      POSTGRES_USER: su
      POSTGRES_PASSWORD: su
      POSTGRES_DB: schedules
    ports:
      - "5433:5432"
#    volumes:
#      - pgdata2:/var/lib/postgresql/data

  gateway:
    build:
      context: ./GatewayModule
    ports:
      - "8080:8080"
    depends_on:
      - postgres1
      - postgres2
      - zipkin


  client-service:
    build:
      context: ./ClientModule
    ports:
      - "8081:8081"
    depends_on:
      - gateway

  schedule-service:
    build:
      context: ./ScheduleModule
    ports:
      - "8083:8083"
    depends_on:
      - client-service

  employee-service:
    build:
      context: ./EmployeeModule
    ports:
      - "8082:8082"
    depends_on:
      - schedule-service

  telegram-bot:
    build:
      context: ./TelegramBotModule
    ports:
      - "8085:8085"
    depends_on:
      - employee-service



